    <?php
	
$jobs_list = array(
    "Accountant",
"Actor",
"Actuary",
"Agricultural and food scientist",
"Anthropologist",
"Architect",
"Artist",
"Automotive mechanic",
"Bookkeeping clerk",
"Budget analyst",
"Carpenter",
"Chemist",
"Childcare worker",
"Civil engineer",
"Coach",
"Computer hardware engineer",
"Computer support specialist",
"Cost estimator",
"Court reporter",
"Database administrator",
"Designer",
"Desktop publisher",
"Economist",
"Editor",
"Educator",
"Electrical engineer",
"Electrician",
"Environmental scientist",
"Farmer",
"Financial analyst",
"Firefighter",
"Fitness trainer",
"Historian",
"Human resources assistant",
"Judge",
"Landscape architect",
"Lawyer",
"Librarian",
"Loan officer",
"Mathematician",
"Microbiologist",
"Musician",
"Nurse",
"Paralegal",
"Pharmacist",
"Photographer",
"Physician",
"Physicist",
"Police officer",
"Professional athlete",
"Psychologist",
"Real estate agent",
"Recreational therapist",
"Referee",
"Registered nurse",
"Reporter",
"Secretary",
"Social worker",
"Software developer",
"Statistician",
"Surveyor",
"Systems analyst",
"Urban planner",
"Veterinarian",
"Web developer",
"Writer",
"Zoologist"
		);
?>